"""Reproducible Polars cleaning script generation (architecture section 9.4).

Emits a standalone Python script that replays the confirmed operation specs in
execution order against a parameterized input path. Manual row-level decisions
reference stable internal row identifiers; validation assertions confirm the
expected schema and row-level outcomes.
"""

import json
import re
from pathlib import Path

from .project import Project

PRELUDE = '''"""Reproduced cleaning pipeline - generated by Quick Data Cleaner.

Usage: python clean.py [input_file] [output_file]
Requires: polars (and openpyxl/python-calamine for Excel inputs).
"""
import sys
import random
from datetime import datetime
import polars as pl

ROW_ID = "__qdc_row_id"
MISSING_MARKERS = {markers!r}
INPUT = sys.argv[1] if len(sys.argv) > 1 else {input_name!r}
OUTPUT = sys.argv[2] if len(sys.argv) > 2 else {output_name!r}


def _is_missing(col, markers=MISSING_MARKERS):
    s = pl.col(col).cast(pl.String)
    return pl.col(col).is_null() | (s.str.strip_chars().str.to_lowercase().is_in(markers) & s.is_not_null())


def _blank_to_null(df, col, markers=MISSING_MARKERS):
    if col not in df.columns or df.schema[col] != pl.String:
        return df
    mask = pl.col(col).str.strip_chars().str.to_lowercase().is_in(markers)
    return df.with_columns(pl.when(mask).then(pl.lit(None).cast(pl.String)).otherwise(pl.col(col)).alias(col))


def _fill_series_linear(values, positions):
    n = len(values)
    known = [(positions[i], values[i]) for i in range(n) if values[i] is not None]
    if len(known) < 2:
        return values
    out = list(values)
    for i in range(n):
        if out[i] is None:
            x = positions[i]
            lo = max((k for k in known if k[0] <= x), key=lambda k: k[0], default=None)
            hi = min((k for k in known if k[0] >= x), key=lambda k: k[0], default=None)
            if lo is None or hi is None:
                continue
            out[i] = lo[1] if hi[0] == lo[0] else lo[1] + (x - lo[0]) / (hi[0] - lo[0]) * (hi[1] - lo[1])
    return out


def _ordered(df, order_by):
    if order_by and order_by in df.columns:
        return df.sort([order_by, ROW_ID])
    return df.sort(ROW_ID)


def _try_bool(v):
    if isinstance(v, bool):
        return v
    s = str(v).strip().lower()
    if s in {{"y", "yes", "true", "t", "1"}}:
        return True
    if s in {{"n", "no", "false", "f", "0"}}:
        return False
    return None
'''


def _emit_treat_missing(p: dict) -> list[str]:
    col, m = p["column"], p["method"]
    L = [f"df = _blank_to_null(df, {col!r})"]
    if m == "drop_column":
        return [f"df = df.drop({col!r})"]
    if m == "drop_rows":
        return [f"df = df.filter(~_is_missing({col!r}))"]
    if m == "constant":
        L.append(f"df = df.with_columns(pl.col({col!r}).fill_null({p['value']!r}))")
    elif m in ("mean", "median"):
        L.append(f"_s = df[{col!r}].drop_nulls()")
        L.append(f"df = df.with_columns(pl.col({col!r}).fill_null(_s.{m}()))")
    elif m == "mode":
        L.append(f"_s = df[{col!r}].drop_nulls().mode().sort().first()")
        L.append(f"df = df.with_columns(pl.col({col!r}).fill_null(_s))")
    elif m in ("forward_fill", "backward_fill"):
        ob = p.get("order_by")
        fill = "forward_fill" if m == "forward_fill" else "backward_fill"
        L += [f"df = _ordered(df, {ob!r}).with_columns(pl.col({col!r}).{fill}())",
              f"df = df.sort(ROW_ID)"]
    elif m in ("interpolate_linear", "interpolate_time"):
        ob = p.get("order_by")
        L += [
            f"df = _ordered(df, {ob!r})",
            f"_nums = [float(v) if v is not None else None for v in df[{col!r}].to_list()]",
            f"_pos = [float(i) for i in range(len(_nums))]"
            if m == "interpolate_linear" or not ob else
            f"_pos = [(p.timestamp() if hasattr(p, 'timestamp') else float(i)) for i, p in enumerate(df[{ob!r}].to_list())]",
            f"df = df.with_columns(pl.Series({col!r}, _fill_series_linear(_nums, _pos), dtype=pl.Float64))",
            "df = df.sort(ROW_ID)",
        ]
    elif m == "group_impute":
        gb, stat = p["group_by"], p.get("statistic", "median")
        if stat == "mode":
            L.append(f"_stats = df.group_by({gb!r}).agg(pl.col({col!r}).drop_nulls().mode().first().alias('__gs'))")
        else:
            L.append(f"_stats = df.group_by({gb!r}).agg(pl.col({col!r}).cast(pl.Float64, strict=False).{stat}().alias('__gs'))")
        L += [
            "df = df.join(_stats, on=%r, how='left')" % gb,
            f"df = df.with_columns(pl.when(pl.col({col!r}).is_null()).then(pl.col('__gs')).otherwise(pl.col({col!r})).alias({col!r}))",
            "df = df.drop('__gs')",
        ]
    elif m == "random_sample":
        L += [
            f"_obs = [v for v in df[{col!r}].to_list() if v is not None]",
            f"_rng = random.Random({p.get('seed', 0)!r})",
            f"df = df.with_columns(pl.Series({col!r}, [_rng.choice(_obs) if v is None else v for v in df[{col!r}].to_list()]))",
        ]
    return L


def _emit_convert_type(p: dict) -> list[str]:
    col, target = p["column"], p["target"]
    fmt = p.get("format")
    if target == "integer":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.strip_chars().str.replace_all(',', '').cast(pl.Int64, strict=False).alias({col!r}))"]
    if target in ("decimal", "float"):
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.strip_chars().str.replace_all(',', '').cast(pl.Float64, strict=False).alias({col!r}))"]
    if target == "boolean":
        return [f"df = df.with_columns(pl.Series({col!r}, [_try_bool(v) for v in df[{col!r}].to_list()], dtype=pl.Boolean))"]
    if target in ("string", "text"):
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).alias({col!r}))"]
    if target == "categorical":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).cast(pl.Categorical).alias({col!r}))"]
    if target == "date":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.strip_chars().str.to_date({fmt!r}, strict=False).alias({col!r}))"]
    if target == "datetime":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.strip_chars().str.to_datetime({fmt!r}, strict=False).alias({col!r}))"]
    if target == "time":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.strip_chars().str.to_time({fmt!r}, strict=False).alias({col!r}))"]
    return [f"# unsupported target {target!r}"]


_NORM_EXPR = {
    "trim": ".str.strip_chars()",
    "collapse_spaces": ".str.replace_all(r' {2,}', ' ')",
    "lower": ".str.to_lowercase()",
    "upper": ".str.to_uppercase()",
    "title": ".str.to_titlecase()",
    "strip_linebreaks": ".str.replace_all(r'[\\r\\n\\t]+', ' ')",
    "standardize_punctuation": ".str.replace_all('[’‘`´]', \"'\").str.replace_all('[“”\"]', '\"').str.replace_all('[—–]', '-').str.replace_all('…', '...')",
}


def _emit_normalize(p: dict) -> list[str]:
    lines = []
    for col in p["columns"]:
        for op in p["operations"]:
            if op["op"] == "empty_to_null":
                lines.append(f"df = df.with_columns(pl.when(pl.col({col!r}).str.strip_chars()=='').then(pl.lit(None).cast(pl.String)).otherwise(pl.col({col!r})).alias({col!r}))")
            elif op["op"] == "map_values":
                lines.append(f"_m = {op['mapping']!r}")
                lines.append(f"df = df.with_columns(pl.Series({col!r}, [_m.get(v, v) for v in df[{col!r}].to_list()]))")
            elif op["op"] in _NORM_EXPR:
                lines.append(f"df = df.with_columns(pl.col({col!r}){_NORM_EXPR[op['op']]}.alias({col!r}))")
    return lines


def _emit_mask_values(p: dict) -> list[str]:
    col, rule = p["column"], p["rule"]
    t = rule["type"]
    if t == "range":
        conds = []
        if rule.get("min") is not None:
            conds.append(f"(pl.col({col!r}).cast(pl.Float64, strict=False) < {rule['min']!r})")
        if rule.get("max") is not None:
            conds.append(f"(pl.col({col!r}).cast(pl.Float64, strict=False) > {rule['max']!r})")
        mask = " | ".join(conds) or "pl.lit(False)"
        mask = f"({mask}) & pl.col({col!r}).cast(pl.Float64, strict=False).is_not_null()"
    elif t == "not_in":
        mask = f"~pl.col({col!r}).cast(pl.String).is_in({[str(v) for v in rule['values']]!r}) & pl.col({col!r}).is_not_null()"
    elif t == "unparseable_date":
        mask = f"pl.col({col!r}).cast(pl.String).str.to_date({rule.get('format')!r}, strict=False).is_null() & pl.col({col!r}).is_not_null()"
    elif t == "contains":
        mask = f"~pl.col({col!r}).cast(pl.String).str.contains({str(rule['text'])!r}, literal=True) & pl.col({col!r}).is_not_null()"
    elif t == "cmp":
        vk = rule.get("value_kind", "number")
        parse = f"pl.col({col!r}).cast(pl.String).str.to_datetime(strict=False)" if vk == "date" else f"pl.col({col!r}).cast(pl.Float64, strict=False)"
        sym = {"gt": ">", "ge": ">=", "lt": "<", "le": "<=", "eq": "==", "ne": "!="}[rule["op"]]
        if rule.get("other_column"):
            oc = rule["other_column"]
            rparse = f"pl.col({oc!r}).cast(pl.String).str.to_datetime(strict=False)" if vk == "date" else f"pl.col({oc!r}).cast(pl.Float64, strict=False)"
            mask = f"~({parse} {sym} {rparse}) & {parse}.is_not_null() & {rparse}.is_not_null()"
        else:
            rhs = f"datetime.fromisoformat({str(rule['value'])!r})" if vk == "date" else repr(float(rule["value"]))
            mask = f"~({parse} {sym} {rhs}) & {parse}.is_not_null()"
    elif t == "date_range":
        conds = [f"parsed.is_null() & pl.col({col!r}).is_not_null()"]
        if rule.get("min"):
            conds.append(f"parsed < datetime.fromisoformat({str(rule['min'])!r})")
        if rule.get("max"):
            conds.append(f"parsed > datetime.fromisoformat({str(rule['max'])!r})")
        mask = f"(lambda parsed: {' | '.join(conds)})(pl.col({col!r}).cast(pl.String).str.to_datetime(strict=False))"
    else:
        mask = f"pl.col({col!r}).cast(pl.String).str.strip_chars().cast(pl.Float64, strict=False).is_null() & pl.col({col!r}).is_not_null()"
    return [f"df = df.with_columns(pl.when({mask}).then(pl.lit(None)).otherwise(pl.col({col!r})).alias({col!r}))"]


def _emit_standardize_format(p: dict) -> list[str]:
    col, kind = p["column"], p["kind"]
    if kind == "boolean":
        rep = p.get("representation", "bool")
        if rep == "bool":
            return [f"df = df.with_columns(pl.Series({col!r}, [_try_bool(v) for v in df[{col!r}].to_list()], dtype=pl.Boolean))"]
        labels = {"yes_no": ("No", "Yes"), "one_zero": ("0", "1")}.get(rep, ("False", "True"))
        return [
            f"_b = [_try_bool(v) for v in df[{col!r}].to_list()]",
            f"df = df.with_columns(pl.Series({col!r}, [None if b is None else ({labels[1]!r} if b else {labels[0]!r}) for b in _b]))",
        ]
    if kind == "date_format":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.to_date({p.get('format')!r}, strict=False).dt.strftime('%Y-%m-%d').alias({col!r}))"]
    if kind == "decimal_separator":
        if p.get("from_separator") == ",":
            return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.replace('.', '').str.replace(',', '.').cast(pl.Float64, strict=False).alias({col!r}))"]
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.Float64, strict=False).alias({col!r}))"]
    if kind == "currency":
        return [f"df = df.with_columns(pl.col({col!r}).cast(pl.String).str.replace_all(r'[^\\d,.\\-]', '').str.replace_all(',', '').cast(pl.Float64, strict=False).alias({col!r}))"]
    if kind == "percent":
        scale = " / 100.0" if p.get("mode") == "proportion" else ""
        return [f"df = df.with_columns((pl.col({col!r}).cast(pl.String).str.replace_all('%', '').str.strip_chars().cast(pl.Float64, strict=False)){scale}.alias({col!r}))"]
    return [f"# unsupported format kind {kind!r}"]


def _emit_treat_rows(p: dict) -> list[str]:
    col, ids, m = p["column"], p["row_ids"], p["method"]
    target = f"pl.col(ROW_ID).is_in({ids!r})"
    if m == "missing":
        return [f"df = df.with_columns(pl.when({target}).then(pl.lit(None)).otherwise(pl.col({col!r})).alias({col!r}))"]
    if m == "cap":
        return [
            f"_e = pl.col({col!r}).cast(pl.Float64, strict=False).clip(lower_bound={p.get('min')!r}, upper_bound={p.get('max')!r})",
            f"df = df.with_columns(pl.when({target}).then(_e).otherwise(pl.col({col!r})).alias({col!r}))",
        ]
    if m in ("mean", "median", "mode"):
        if m == "mode":
            stat = f"df[{col!r}].drop_nulls().mode().sort().first()"
        else:
            stat = f"df[{col!r}].drop_nulls().{m}()"
        return [f"df = df.with_columns(pl.when({target}).then(pl.lit({stat})).otherwise(pl.col({col!r})).alias({col!r}))"]
    if m == "value":
        return [f"df = df.with_columns(pl.when({target}).then(pl.lit({p['value']!r})).otherwise(pl.col({col!r})).alias({col!r}))"]
    return [f"# unsupported treat_rows method {m!r}"]


def _emit_merge_records(p: dict) -> list[str]:
    lines = []
    for col, val in p.get("field_values", {}).items():
        lines.append(
            f"df = df.with_columns(pl.when(pl.col(ROW_ID)=={p['primary_row_id']!r}).then(pl.lit({val!r})).otherwise(pl.col({col!r})).alias({col!r}))"
        )
    drops = p.get("drop_row_ids", [])
    if drops:
        lines.append(f"df = df.filter(~pl.col(ROW_ID).is_in({drops!r}))")
    return lines


def _emit_clean_special_chars(p: dict) -> list[str]:
    col, chars, action = p["column"], p["chars"], p["action"]
    if action == "blank":
        pat = "|".join(re.escape(c) for c in chars)
        return [
            f"df = df.with_columns(pl.when(pl.col({col!r}).str.contains({pat!r}))"
            f".then(pl.lit(None).cast(pl.String)).otherwise(pl.col({col!r})).alias({col!r}))"
        ]
    repl = "" if action == "strip" else str(p.get("replacement", ""))
    lines = [f"expr_{col!r} = pl.col({col!r})".replace("expr_", "_e_")]
    for ch in chars:
        lines.append(f"_e_ = _e_.str.replace_all({re.escape(ch)!r}, {repl!r})")
    lines.append(f"df = df.with_columns(_e_.alias({col!r}))")
    return lines


def _emit_convert_units(p: dict) -> list[str]:
    col, rules = p["column"], p["rules"]
    cond_rules = [r for r in rules if "condition" in r]
    if cond_rules:
        # numeric scale rules -> when/then chain (mirrors convert_units)
        lines = ["_e_ = pl.col(%r)" % col]
        for r in cond_rules:
            c, f = r["condition"], float(r["factor"])
            op, v = c.get("op"), float(c.get("value", 0))
            cmp_map = {"<=": "<=", ">=": ">=", "<": "<", ">": ">", "==": "=="}
            if op == "all":
                cond = "pl.lit(True)"
            elif op in cmp_map:
                cond = "pl.col(%r) %s %r" % (col, cmp_map[op], v)
            else:
                cond = "pl.lit(False)  # unknown condition op %r" % op
            lines.append(
                "_e_ = pl.when(%s).then(pl.col(%r).cast(pl.Float64) * %r).otherwise(_e_)" % (cond, col, f)
            )
        lines.append("df = df.with_columns(_e_.alias(%r))" % col)
        return lines
    unit_rules = {str(r["unit"]).strip().lower(): float(r["factor"]) for r in rules if r.get("unit") is not None}
    return [
        "import re as _re",
        '_qdc_usplit = _re.compile(r"^\\s*([^\\d\\s.,+\\-]*)\\s*([+-]?[\\d]+(?:[.,]\\d+)?)\\s*([^\\d]*)\\s*$")',
        '_qdc_unum = _re.compile(r"^\\s*[+-]?[\\d]+(?:[.,]\\d+)?\\s*$")',
        "def _qdc_cunit(v):",
        "    if v is None or (isinstance(v, str) and v.strip().lower() in MISSING_MARKERS):",
        "        return None",
        "    s = str(v)",
        "    if _qdc_unum.match(s):",
        f"        f = {unit_rules!r}.get('')",
        "        n = float(s.replace(',', '.'))",
        "        return n * f if f is not None else n",
        "    m = _qdc_usplit.match(s)",
        "    if m is None:",
        "        return s",
        "    unit = (m.group(1) or m.group(3) or '').strip().lower()",
        "    try:",
        "        n = float(m.group(2).replace(',', '.'))",
        "    except ValueError:",
        "        return s",
        f"    f = {unit_rules!r}.get(unit)",
        "    if unit and f is None:",
        "        return s",
        "    return n * (f if f is not None else 1.0)",
        f"_qdc_vals = [_qdc_cunit(v) for v in df[{col!r}].to_list()]",
        "_qdc_allnum = all(v is None or not isinstance(v, str) for v in _qdc_vals)",
        f"df = df.with_columns(pl.Series({col!r}, _qdc_vals if _qdc_allnum else "
        f"[v if (isinstance(v, str) or v is None) else repr(v) for v in _qdc_vals], "
        f"dtype=pl.Float64 if _qdc_allnum else pl.String).alias({col!r}))",
    ]


def _emit_clean_pattern(p: dict) -> list[str]:
    col, action, pat = p["column"], p["action"], p.get("pattern")
    s = "pl.col(%r)" % col
    if action == "set_missing":
        return [
            f"df = df.with_columns(pl.when({s}.str.contains({pat!r})).then({s})"
            f".otherwise(pl.lit(None).cast(pl.String)).alias({col!r}))"
        ]
    if action == "extract":
        return [
            f"df = df.with_columns(pl.when({s}.str.contains({pat!r}))"
            f".then({s}.str.extract({pat!r}, {int(p.get('group', 1))})).otherwise({s}).alias({col!r}))"
        ]
    if action == "strip_affix":
        lines = [f"_e_ = {s}"]
        if p.get("prefix"):
            lines.append(f"_e_ = _e_.str.strip_prefix({p['prefix']!r})")
        if p.get("suffix"):
            lines.append(f"_e_ = _e_.str.strip_suffix({p['suffix']!r})")
        lines.append(f"df = df.with_columns(_e_.alias({col!r}))")
        return lines
    if action == "pad":
        return [f"df = df.with_columns({s}.str.zfill({int(p['length'])}).alias({col!r}))"]
    if action == "replace":
        return [f"df = df.with_columns({s}.str.replace_all({pat!r}, {p.get('replacement', '')!r}).alias({col!r}))"]
    return [f"# unsupported clean_pattern action {action!r}"]


def _emit_op(op: dict) -> list[str]:
    t, p = op["op_type"], op["params"]
    if t == "rename_column":
        return [f"df = df.rename({{{p['from']!r}: {p['to']!r}}})"]
    if t == "rename_columns":
        return [f"df = df.rename({p['mapping']!r})"]
    if t == "drop_rows":
        return [f"df = df.filter(~pl.col(ROW_ID).is_in({p['row_ids']!r}))"]
    if t == "drop_column":
        return [f"df = df.drop({p['column']!r})"]
    if t == "fill_null_constant":
        return [f"df = df.with_columns(pl.col({p['column']!r}).fill_null({p['value']!r}))"]
    if t == "clean_special_chars":
        return _emit_clean_special_chars(p)
    if t == "treat_missing":
        return _emit_treat_missing(p)
    if t == "convert_type":
        return _emit_convert_type(p)
    if t == "normalize":
        return _emit_normalize(p)
    if t == "mask_values":
        return _emit_mask_values(p)
    if t == "standardize_format":
        return _emit_standardize_format(p)
    if t == "convert_units":
        return _emit_convert_units(p)
    if t == "clean_pattern":
        return _emit_clean_pattern(p)
    if t == "merge_records":
        return _emit_merge_records(p)
    if t == "treat_rows":
        return _emit_treat_rows(p)
    return [f"# unsupported op {t!r}"]


def generate_script(project: Project) -> str:
    """Standalone script replaying each item's applied ops in order."""
    from .config import MISSING_MARKERS

    kind = project.data["kind"]
    input_name = project.data["source_filename"]
    out_ext = {"csv": "csv", "xlsx": "xlsx", "xls": "xlsx"}[kind]
    output_name = f"{Path(input_name).stem}_cleaned.{out_ext}"

    chunks = [PRELUDE.format(
        markers=sorted(MISSING_MARKERS),
        input_name=input_name,
        output_name=output_name,
    )]

    chunks.append("\n# --- load input ---")
    if kind == "csv":
        chunks.append('df = pl.read_csv(INPUT)')
    else:
        chunks.append('import openpyxl  # noqa')
        chunks.append('df = pl.read_excel(INPUT, sheet_name=SHEET)')

    for item in project.data["items"]:
        if item["status"] == "rejected":
            continue
        history = project.history(item["item_id"])
        ops = [o.to_dict() for o in history.ops[: history.pointer]]
        if not ops:
            continue
        chunks.append(f"\n# === {item['name']} ===")
        if kind != "csv":
            chunks.append(f"SHEET = {item['name']!r}")
        chunks.append("df = df.with_row_index(ROW_ID)")
        for op in ops:
            chunks.append(f"# op {op['seq']}: {op['op_type']} ({op['stage']})")
            chunks.extend(_emit_op(op))
        final_cols = [c for c in history.working().columns if c != "__qdc_row_id"]
        chunks.append(f"assert df.height == {history.working().height}, 'row count changed unexpectedly'")
        chunks.append(f"assert set(df.columns) - {{ROW_ID}} == set({final_cols!r}), 'schema changed unexpectedly'")
        chunks.append("df = df.drop(ROW_ID)")

    chunks.append("\n# --- write output ---")
    if kind == "csv":
        chunks.append("df.write_csv(OUTPUT)")
    else:
        chunks.append("df.write_excel(OUTPUT)")
    chunks.append("print(f'Wrote {OUTPUT}')")
    return "\n".join(chunks) + "\n"


def generate_config_json(project: Project) -> dict:
    """Transformation configuration export (ordered deterministic op specs)."""
    items = []
    for item in project.data["items"]:
        history = project.history(item["item_id"])
        items.append({
            "item_id": item["item_id"],
            "name": item["name"],
            "status": item["status"],
            "stage_states": project.item_meta(item["item_id"])["stage_states"],
            "outcome": project.item_meta(item["item_id"]).get("outcome"),
            "operations": [o.to_dict() for o in history.ops[: history.pointer]],
        })
    return {
        "project_id": project.data["project_id"],
        "source_filename": project.data["source_filename"],
        "kind": project.data["kind"],
        "tool": "quick-data-cleaner",
        "tool_version": "0.1.0",
        "items": items,
    }
